### ISSUE TITLE
Drop support for static models configuration

### ISSUE THREAD

**Issue by orditeck** [hapipal/schwifty#63]
When importing schwifty in webpack, I get the following warning:

```sh
WARNING in ./node_modules/Schwifty/lib/index.js 94:28-50
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/Schwifty/lib/index.js 98:28-76
Critical dependency: the request of a dependency is an expression
```

See https://github.com/webpack/webpack/issues/196.  There are some ways to get rid of these warnings in webpack, but it would be even better to avoid them in the first place.

**Comment by devinivy** [comment]
I plan to drop support for static `models` config, as seen here: https://github.com/hapipal/schwifty/blob/de2f5ad795c0eb5e676375bc5f5c153bbb9f4848/test/index.js#L239-L273

For me the reason is less due to webpack warnings, although I'm glad it will help clear that up too.  The feature is very old, going back to usage with [dogwater](https://github.com/devinivy/dogwater) and pre-[haute-couture](https://github.com/hapipal/haute-couture).  I don't think it's very useful nowadays, but if anyone objects I would be happy to chat more about it here.
